editor: source

execute:
  cache: false # "Danger Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

project:
  type: website
  output-dir: docs
  render: [index.qmd]

title: pynetlogo Examples
author: "Daniel Vartanian"
keyword: >
  Python, Pipelines, NetLogo, pynetlogo, Agent-Based Modeling, Data Science,
  Reproducible Research
date: today
date-format: long

website:
  site-url: https://danielvartan.github.io/pynetlogo/
  repo-url: https://github.com/danielvartan/pynetlogo/
  issue-url: https://github.com/danielvartan/pynetlogo/issues/
  repo-branch: main
  repo-actions: [edit, source, issue]
  search: true
  navbar:
    title: false
    right:
      - icon: github
        href: https://github.com/danielvartan/pynetlogo/
        aria-label: GitHub

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    locale: en
    language: en-us
    code-fold: false
    code-link: true
    code-tools: false
    df-print: paged
    fig-align: center
    cap-location: top
    lightbox: true
    callout-appearance: simple
    theme: [cosmo]
